# ============================================================
# MICROSOFT ENTRA ID - JWT
# ============================================================
#
# El Access Token que estamos recibiendo actualmente utiliza
# como issuer:
#
# https://sts.windows.net/{TENANT_ID}/
#
# Por eso Spring debe validar ese issuer.
#
# ============================================================

pedidos360.security.issuer=https://sts.windows.net/6f3f02b8-6fe2-4022-bfd3-ddaf1ac7960c/


# ============================================================
# CLAVES PÚBLICAS DE MICROSOFT
# ============================================================
#
# Spring utiliza estas claves para comprobar la firma
# criptográfica del JWT.
#
# No estamos almacenando ninguna clave privada.
#
# ============================================================

pedidos360.security.jwk-set-uri=https://login.microsoftonline.com/6f3f02b8-6fe2-4022-bfd3-ddaf1ac7960c/discovery/v2.0/keys


# ============================================================
# AUDIENCE DE PEDIDOS360-API
# ============================================================
#
# El claim "aud" del JWT debe coincidir con esta API.
#
# ============================================================

pedidos360.security.audience=api://6c0ce39d-b8ac-4714-a6cc-e9cd674adebe


# ============================================================
# CORS
# ============================================================

pedidos360.cors.allowed-origin=http://localhost:4200


# ============================================================
# SERVIDOR
# ============================================================

server.port=8080